let quizContent =[
    {   
        "quiz_name": "Quiz_1",
        "question": "Wer erfand die Glühbirne?",
        "answer_1": "Thomas Edison",
        "answer_2": "Ernst Abbe",
        "answer_3": "James Watt",
        "answer_4": "Neil Arnot",
        "right_answer": "1"
    },
    {   
        "quiz_name": "Quiz_1",
        "question": "Wer erfand die Luftpumpe?",
        "answer_1": "Neil Arnot",
        "answer_2": "Carl Benz",
        "answer_3": "Otto von Guericke",
        "answer_4": "Robert Adler",
        "right_answer": "3",
    },
    {   
        "quiz_name": "Quiz_1",
        "question": "Mit was bringt man 'Lothar Meyer' in Verbindung?",
        "answer_1": "Buchdruck",
        "answer_2": "Erfinder des Motors",
        "answer_3": "Kleinbildkamera",
        "answer_4": "Periodensystem",
        "right_answer": "4",
    },
    {   
        "quiz_name": "Quiz_2",
        "question": "Wann wurde die Floppy-Disk erfunden?",
        "answer_1": "1969",
        "answer_2": "1942",
        "answer_3": "1990",
        "answer_4": "2000",
        "right_answer": "1",
    },
    {   
        "quiz_name": "Quiz_2",
        "question": "Wann war der Mauerfall?",
        "answer_1": "21.4.1990",
        "answer_2": "9.11.1989",
        "answer_3": "7.11.1989",
        "answer_4": "22.4.1990",
        "right_answer": "2",
    },
    {   
        "quiz_name": "Quiz_2",
        "question": "Ab wann gab es den ersten Euro als Bargeld in Deutschland?",
        "answer_1": "1.1.1999",
        "answer_2": "1.11.2000",
        "answer_3": "31.12.2001",
        "answer_4": "1.1.2002",
        "right_answer": "4",
    },
    {   
        "quiz_name": "Quiz_3",
        "question": "Wie heißt die Frucht der Buche?",
        "answer_1": "Buchensamen",
        "answer_2": "Buchenkerne",
        "answer_3": "Bucheckern",
        "answer_4": "Buchennasen",
        "right_answer": "3",
    },
    {   
        "quiz_name": "Quiz_3",
        "question": "Welcher dieser Bäume ist ein Laubbaum",
        "answer_1": "Ahorn",
        "answer_2": "Tannenbaum",
        "answer_3": "Fichte",
        "answer_4": "Latsche",
        "right_answer": "1",
    },
    {   
        "quiz_name": "Quiz_3",
        "question": "Welcher dieser Pilze ist Giftig?",
        "answer_1": "Fliegenpilz",
        "answer_2": "Steinpilz",
        "answer_3": "Champignon",
        "answer_4": "Pfifferling",
        "right_answer": "1",
    },
];